<?php

namespace AppBundle\Repository;

/**
 * CallCommunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallCommunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
