<?php

namespace AppBundle\Repository;

use AppBundle\Model\ModelResult;

/**
 * CommunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $userId
     * @param int $contactId
     * @param int $start
     * @param int $limit
     * @param string $communicationDateOrder
     * @return ModelResult
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCommunicationsResult($userId, $contactId, $start = 0, $limit = 10, $communicationDateOrder = 'DESC')
    {
        $communications = $this->getEntityManager()->createQueryBuilder();
        $communications->from('AppBundle:Communication', 'communication')
            ->where('communication.user = :userId')
            ->andWhere('communication.contact = :contactId')
            ->setParameter('userId', $userId)
            ->setParameter('contactId', $contactId);


        $totalRecords = clone $communications;
        $totalRecords->select($totalRecords->expr()->count('communication.id'));
        $totalRecords = (int)$totalRecords->getQuery()->getSingleScalarResult();

        $communications = $communications->select('communication')
            ->setFirstResult($start)
            ->setMaxResults($limit)
            ->orderBy('communication.date', $communicationDateOrder)
            ->getQuery()
            ->getArrayResult();

        return new ModelResult($totalRecords, $communications);
    }
}
