<?php

namespace AppBundle\Repository;

/**
 * SMSCommunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SMSCommunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
