api_v1_get_contacts:
  path:     /contacts/page/{page}/total/{total}
  controller: AppBundle:Contact:getContacts
  methods:    [GET]
  requirements:
    page: \d+
    total: \d+

api_v1_get_contact_communications:
  path:     /contact/{contactId}/communications/page/{page}/total/{total}
  controller: AppBundle:Communication:getCommunications
  methods:    [GET]
  requirements:
    contactId: \d+
    page: \d+
    total: \d+