AppBundle\Entity\AuthCode:
  type: entity
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    client:
      targetEntity: Client
      joinColumn:
        nullable: false
    user:
      targetEntity: User