AppBundle\Entity\Contact:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\ContactRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: '24'
    phoneNumber:
      type: integer
      options:
        unsigned: true
  manyToOne:
    user:
      targetEntity: User
      joinColumn:
        nullable: false
  lifecycleCallbacks: {  }
