AppBundle\Entity\User:
  type: entity
  repositoryClass: AppBundle\Repository\UserRepository
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  fields:
    phoneNumber:
      type: integer
      options:
        unsigned: true